version: '2'

services:
    mailhog:
      image: blueimp/mailhog
      ports:
        - 1025:1025
        - ${PORT_MAILHOG}:8025
      restart: always
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - ${PORT_PHPMYADMIN}:80
        restart: always
    db:
        image: mysql
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        restart: always
    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www
            - ${SYMFONY_APP_PATH}/.composer:/.composer
#            - ./logs/symfony:/var/www/symfony/var/logs
        restart: always
    nginx:
        build: nginx
        ports:
            - ${PORT_NGNIX}:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
        restart: always
    elk:
        image: willdurand/elk
        ports:
            - ${PORT_ELK}:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx
        restart: always
